### ISSUE TITLE
Connection Pool Bug

### ISSUE THREAD

**Issue by JoelBender** [Grokzen/redis-py-cluster#101]
I have a six node cluster (3 masters, 3 slaves), all of them configured with `maxclients 100`.  After publishing approximately 100 messages, the client application dies:

    File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 1888, in publish
      return self.execute_command('PUBLISH', channel, message)
    File "/usr/local/lib/python3.4/dist-packages/rediscluster/utils.py", line 93, in inner
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.4/dist-packages/rediscluster/client.py", line 230, in execute_command
      return self._execute_command_on_nodes(self.nodes_callbacks[command](self, command), *args, **kwargs)
    File "/usr/local/lib/python3.4/dist-packages/rediscluster/client.py", line 317, in _execute_command_on_nodes
      res[node["name"]] = self.parse_response(connection, command, **kwargs)
    File "/usr/local/lib/python3.4/dist-packages/redis/client.py", line 577, in parse_response
      response = connection.read_response()
    File "/usr/local/lib/python3.4/dist-packages/redis/connection.py", line 574, in read_response
      raise response
    redis.exceptions.ResponseError: max number of clients reached

This looks like a connection pool bug:

    $ netstat --tcp -a -n | grep TIME_WAIT | wc -l
    100

This can be reproduced with [this sample code](https://gist.github.com/72squared/ef4b679d0a0f36ab15c1) or with [this project](https://github.com/JoelBender/redis-cluster-pubsub). 

Python 2.7.6 or Python 3.4.3, redis 2.10.3, rediscluster 1.1.0

**Comment by Grokzen** [comment]
@JoelBender Hi. First thing is that i would not recommend to use pubsub with a redis cluster. There is currently alot of problems with the implementation inside redis iteself that makes it very slow and has crazy ammount of overhead. In short, it is implemented in a way that for each published message it will be sent to all nodes in the cluster because it is implemented so that any client can connect to any node and listen to any channel. This means that the fanout has to be implemented in the way it is. The only sane suggestion i have yet seen is to use the same hashslot mechanics that is already implemented for all other commands where the slot is determined by the key. By doing this in the pubsub case, it would remove the need to distribute the published messages to all nodes and then it would be really easy for clients to implement this pattern.

Anyhow, i still find it interesting that the client behaves this way. It should be releasing back the connection after a published message O.o. I will do some digging during the week and see what i can find out.

**Comment by JoelBender** [comment]
Thank you!  I completely understand why it shouldn't be used as it stands now, and I will be using MQTT for my very simple pubsub application requirements.  I intend to also dig into this bug at some point, but it will be quite some time before I get the chance.

**Comment by Grokzen** [comment]
This issue is similar to #129 and and the provided solution could fix this issue also.

**Comment by Grokzen** [comment]
@JoelBender I worked some on this problem today and took a deeper look and compared my implementation to how redis-py handles connections in the pool and i saw several flaws with my implementation. I have now reworked the connection_pool code to be more similar to redis-py and how it works in there. It also means that it impacts pubsub code because those connections is no longer tracked in a different variables. You can see the code here #136 where it should fix this problem and more.

**Comment by Grokzen** [comment]
@JoelBender Connection pool logic works much better in 1.2.0 and when i test things out by publishing alot of messages with a limited number of connections i do not see this problem with reaching the max number of connections because they are now added back to the pool properly when the command is done. You will however still get to the max number of connections used if you would to run with say max connections = 16 and use the same client object in say 32+ threads and max out the number of publish commands sent. But this is intended behavior and you would see the very same thing in redis-py.

If yo find some other or similar errors in release 1.2.0, please open a new ticket.
