### ISSUE TITLE
socket_connect_timeout not respected when init_slot_cache=True (default)

### ISSUE THREAD

**Issue by demikl** [Grokzen/redis-py-cluster#127]
Using :

- redis 2.10.3

- redis-py-cluster 1.1.0

I'm opening a connection to my Redis cluster using :
`redis.StrictRedisCluster(
                                 startup_nodes=mynodes, decode_responses=True,
                                 socket_connect_timeout=0.1)`

When reaching ClusterConnectionPool.__init__(), as `init_slot_cache` is True by default, a connection is attempted to all nodes in the cluster, bypassing the `socket_connect_timeout` or `socket_timeout` that is passed through `connection_kwargs`.

I was confronted to this bug when I was attempting to test whether a connection to Redis could be set-up, in a "status" API call to my application. When no server defined in my configuration `mynodes` could be reached, it took quite a long time to tell me no connection could be established.

Moreover, when using `init_slot_cache=False`, there's another bug in `ClusterConnectionPool.get_master_node_by_slot()`, because when there's no server that could be reached, `self.nodes.slots` is an empty list.

**Comment by Grokzen** [comment]
Hi @demikl. This issue should be resolved in the `unstable` branch where this line https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/nodemanager.py#L103 now passes the connection_kwargs into each `StrictRedis` instance. In the mentioned redis version here  https://github.com/Grokzen/redis-py-cluster/blob/1.1.0/rediscluster/nodemanager.py#L72 no extra connection args is passed.

If possible based on the info above, can you try your code again with the unstable branch and confirm that it works. Otherwise i will close this issue when i make the next release because i see it should be fixed in there.

**Comment by Grokzen** [comment]
About the `init_slot_cache=False` it is intended that it should not initialize the cluster when trying to send a command when you have specified that flag. The idea and intended use of this option is to create a cluster client object but not initialize it and then do something or wait any amount of time and then when you are ready/want to you can initialize the client yourself. I would not classify this as a bug.

**Comment by demikl** [comment]
I can confirm that this fix works for my use case. Thanks.

**Comment by Grokzen** [comment]
Sounds good. Closing this issue now and consider it fixed in next release as label says then.
