### ISSUE TITLE
After Publish connections are not returned to the pool

### ISSUE THREAD

**Issue by melhin** [Grokzen/redis-py-cluster#129]
When i use the pubsub mechanism inside redis, after a message gets published on a channel the connections tend to hog on one particular node in the cluster therby giving me this error
                       **Error 24 connecting to 127.0.0.1:7006. Too many open files.**
My cluster has 3 masters and 3 slaves.. Im attaching a small example script i used to test this behavior [example.py]. I checked the clients "redis-cli -c -p 7006 client list | wc -l"
Another peculiar thing i noticed was when i do 
for f in `seq 1 1000000`;do echo $f;redis-cli -c -p 7006 publish channel $f;done 
the connections are returned and 
[example.txt](https://github.com/Grokzen/redis-py-cluster/files/168839/example.txt)

no connection hogging is seen

**Comment by Grokzen** [comment]
The pubsub implementation inside this lib is going to be removed and the work is happening in this PR #115. Pubsub should not be used in a cluster environment right now and you can read up on why here https://github.com/Grokzen/redis-py-cluster/blob/unstable/docs/Pubsub.md

The only time i will consider to add pubsub back into this lib, is redis itself reworks their implementation to be more cluster friendly.

**Comment by melhin** [comment]
Thanks for the update @Grokzen  . But i just wanted to know why when i do a plain publish using the redis-cli the connections are returned and when i do a publish with the redis-cluster it hoggs on one particular node, any specific reason for that ?

**Comment by Grokzen** [comment]
The first iteration i did for the pubsub support i found out that the return from a publish command about how many clients that recieved the message was not accurate and it was only taking into account how many clients that was connected to that specific node that the publish command was talking to. Because of this, the compatibility with the existing publish/subscribe API and mechanics that is used by `redis-py` compatible software would be broken and `redis-py-cluster` could not act as a drop-in replacement to provide seamless compatibility. The only fix at that time was to have all clients talk to the same node because that would ensure that it would still work as expected.

Sinc then some things have changed because i now know that you can use the slot hashing mechanism to distribute the clients on all nodes but still do it in a predictable way and the pub/sub API would work as expected, however then you hit the performance problem that still plagues redis internally and that is described in the docs.

**Comment by melhin** [comment]
Ok so i was still curious with the connection leakage problem with publish so after some digging around i found in rediscluster/connection.py  get_connection there was this tag

# TOOD: Pop existing connection if it exists. 

So in release you were removing it from _in_use_pubsub_connections and then you blindly appended the connection to _available_pubsub_connections so a lot of publish connections stayed on and eventually causing the file limits on the system to get exhausted 

I have created a pull request with this change . Let me know if im on the right track
https://github.com/Grokzen/redis-py-cluster/pull/130

**Comment by Grokzen** [comment]
I worked some on this problem today and took a deeper look and compared my implementation to how redis-py handles connections in the pool and i saw several flaws with my implementation. I have now reworked the connection_pool code to be more similar to redis-py and how it works in there. It also means that it impacts pubsub code because those connections is no longer tracked in a different variables. You can see the code here #136 and it should superseed your PR #130 where it should fix the same problems and more.

**Comment by Grokzen** [comment]
Fixed in unstable and included in release 1.2.0
