### ISSUE TITLE
How to init slot

### ISSUE THREAD

**Issue by HatBoy** [Grokzen/redis-py-cluster#174]
Yes, is me, I do not know why my issue deleted. My redis cluster 4 nodes all public network IP , for security, I hidden IP, sorry. they can connect each other， also, my windows machine can connect them.
Thank you for taking the time to solve my problems patiently. Now, I only want know how to init solt , when I have a StrictRedisCluster  instance. Thanks again.

**Comment by Grokzen** [comment]
@HatBoy Your issue was not deleted, it can be found here and please read the last response i made in that issue https://github.com/Grokzen/redis-py-cluster/issues/173

I do not really get what you mean by `Now i only want to know how to init slot??` In what instance do your slots not get initialized?

I will print some examples. If you are using the most basic case of using this client class like the following one: 

```
from rediscluster import StrictRedisCluster
startup_nodes = [{"host": "127.0.0.1", "port": "7000"}]
rc = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True)
rc.set("foo", "bar")
print(rc.get("foo"))
```

all the slots will be automatically initialized by the client when you create the `StrictRedisCluster` object. It is a automatic step in the client creation process.

if you however do something like this
```
from rediscluster import StrictRedisCluster
startup_nodes = [{'host': '127.0.0.1', 'port': '7000'}]
# NOTE: the value init_slot_cache=False is different here
rc = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True, init_slot_cache=False)
rc.set("foo", "bar")
print(rc.get("foo"))
```
When you create your client class with this argument then the slots cache will NOT be initialized at the same time as your client class is created but you have to do this _Manually_ at a later time. This feature was requested for some cases where the cluster is not yet up and running when the client class is created and you wanted to have some kind of simple retry logic that would try to initialize after some time instead of directly.

The only other case i can think of when you want about how to initialize the slots is that you have problems to join up your redis cluster but from the last issue you posted i see that it is no problem becuase if you can run `CLUSTER NODES` you have a working cluster.

If it is not any of these cases please make some more detailed description of what exactly the problem is.

**Comment by HatBoy** [comment]
@Grokzen, Sorry, My English is no good, I meran, you say 
`The only support that exists in this library to combat this problem is that you have to define ALL nodes as startup nodes with their public ip addresses and then use the kwargs flag into StrictRedisClsuter that tells it to NOT do a CLUSTER NODES lookup when it initializes the client class.`
can you give me a example? My redis cluster have 4 nodes , my startup_nodes define all nodes ip, but also have the exception, for solve the problem，I change the nodemanager.py 178 line,
`cluster_slots = [[0, 4095, ['ip', 8888, 'cfff0a587bf80ebc30e6757824d36658228c6637']], [4096, 8191, ['ip', 8888, 'b5b739f9af4fb4e401d57001212f64def7c46ce1']], [12288, 16383, ['ip', 8888, '0f856e86125287ef3bc7d949e2778f53f5ecfbb4']], [8192, 12287, ['ip', 8888, '78efaddce08a7f5d8f2a4b2848bd862a65aca8b5']]]`, 
can I set cluster slots when initializes the client class? Thank you very much.

**Comment by Grokzen** [comment]
@HatBoy No you can't define all slots manually when your create the client, it makes no sense to have a manual defenition of the slots setup becuase you can't predict the slots setup and at the smallest change it will all fall apart if you even try to define it yourself. 

If you run the code in my first example in my previous post you do not have to do anything else but to set the correct startup_nodes to the public IP address of _atleast_ one of your nodes, but preferably more then 1 of the nodes.

What exception do you still have if you define all your startup_nodes and their public IP?`

The idea to let the client handle all the slots parsing and handling automatic is that when you have a case where you get MOVED/ASK errors back from your cluster in the case you have moveed one of the slots to a different node or resharded/rebalanced your cluster, the client will automatically detect this and correct the internal slots mappings to make all clients work as expected.

The flag i am refering to in your first question is the flag ìnit_slot_cache=False`and you have a good example of it above, the only thing it is missing is the initialization of the slots cache becuase you need to do that atleast once before you start to send the cluster commands. That step is not shown in the example above but i DO NOT recommend that you use this flag. If you specify the public IP of all the nodes and send them in as `startup_nodes` to your client you should be good to go.

**Comment by Grokzen** [comment]
The main thing is that IF you are able to use your redis-cli client from your windows machine and run the command `CLUSTER NODES` manually from the redis-cli then you should be able to use this client class with the code from my first example without any issues.

If the return data from `CLUSTER NODES` do NOT return the public IP addresses then you have your problem there and you need to fix your cluster so that they announce out the public IP addresses. Otherwise this client will not work for you.

**Comment by HatBoy** [comment]
@Grokzen, I will try again, Thank you for taking the time to solve my problems patiently
