### ISSUE TITLE
support maxidle connections

### ISSUE THREAD

**Issue by deepakverma** [Grokzen/redis-py-cluster#182]
Scenario:
I have a burst of load which causes ConnectionPool to scale up the connections to 100
After a while load is normal now, the load now uses 10 connections to fulfill the request. Pool still has 100 connections open.
Due to period of inactivity redis-server closed 90 connections.
Burst comes in again causing the Pool to scale up the connections. 

New connections have to compete for CPU on client as well as redis-server where it;s already pegged due to load, causing connection timeouts.
 
I am thinking it would be useful if pool has a setting to configure maxidle connections so that ConnectionPool is already ready to fulfill the load

**Comment by Grokzen** [comment]
@deepakverma I am not sure about this one. This really feels like a problem for the underlying lib redis-py and not for this lib. The mission for this lib is to give all commands a way to work in a cluster and make a client that can replace a non clustered client instance with as few changes as possible.

Also think of it like this, redis-py also have this problem in a single node instance so i see no reason for me to implement this feature here because the only problem i should solve here is to take that solution and "scale/make it work" for a cluster. And in this case it might be that i must make it possible to handle maxidle connections for this client across the entire cluster instead of towards one node as in the regular client. But if it is not solved there first, i will not take it in here to make that work.

**Comment by deepakverma** [comment]
makes sense, thx. I have opened it for the underlying lib here https://github.com/andymccurdy/redis-py/issues/824

**Comment by Grokzen** [comment]
@deepakverma Thanks :)
