### ISSUE TITLE
Is Geo supported in this release?

### ISSUE THREAD

**Issue by Andy320** [Grokzen/redis-py-cluster#206]
Hi , thank you all for your effort in this project. 
And I want to know if the Geo function been supported by redis-py-cluster? 

thank u

**Comment by Grokzen** [comment]
@Andy320 The library uses all the functions that is supported in the redis-py version you are using by default. If it is implemented there you can use it here. However in the cases where a new command tries to run a command on multiple keys then we need to make a special implementation of it in this library. Examples is the MGET that can fetch multiple keys and because of this i need to make a client side implementation to get the same functionality but it will perform slower.

My best suggestion is that you install the latest redis-py and redis-py-cluster and you try the functions out and report back your findings. If the commands do not exists in redis-py you have to submit that to that project. If there is something i have blocked or not implemneted in this lib i can help you out.

I have never used the GEO functions in a cluster or non cluster env.

**Comment by AngusP** [comment]
Just for what it's worth, redis-py 2.10.6 and redis-py-cluster 1.3.4 worked well together as far as a quick check of most of the GEO commands

**Comment by Grokzen** [comment]
@Andy320 Becuase this issue was stated as a question and me and angusp answered it, i will now close this one becuase the question was answered. In the case you find some practical error with any GEO commands or anything else, then please open up a new issue with your problem in there.
