### ISSUE TITLE
redis-py-cluster support pipeline in cluster mode.

### ISSUE THREAD

**Issue by rfyiamcool** [Grokzen/redis-py-cluster#232]
see title, thank U.

**Comment by Grokzen** [comment]
@rfyiamcool Issues is not a tool to ask general questions about supported features of the lib. I would suggest you read the docs before ask questions. Here for example http://redis-py-cluster.readthedocs.io/en/master/pipelines.html Otherwise you can always ask on the gitter chat channel for help and general questions.
