### ISSUE TITLE
how to use connection pool ?

### ISSUE THREAD

**Issue by Tracy6465** [Grokzen/redis-py-cluster#240]
After the python file is loaded, initialize the connection pool. then Call the get_recommend_info method via http request in django. One of the problems I now have is a few hours later the connection pool can not be used.

This is my code：

```
from rediscluster import StrictRedisCluster, connection

# init connection pool
connection_pool = connection.ClusterConnectionPool(
    startup_nodes=host_list, 
    skip_full_coverage_check=True,
    password=redis_password,
    socket_timeout=socket_timeout,
)
```

```
# get connection from connection_pool 
def get_recommend_info(yst_id):
    try:
        rc = StrictRedisCluster(
            decode_responses=True,
            readonly_mode=True, socket_connect_timeout=consts.REQUEST_TIME_OUT,
            socket_timeout=consts.REQUEST_TIME_OUT,
        )
        return  rc.hget(bytes(consts.REDIS_KEY).encode('utf-8'),
                               bytes(yst_id).encode('utf-8'))
    except Exception as e:
        print e.message
        return []
```

**Comment by Grokzen** [comment]
@Tracy6465 I need a exception in order to help with this.

Also why are you creating a connection pool manually like this? There is no need to create it manually when you are using those options as you should be able to just pass that into the StrictRedisCluster instance and it will create the pool for you.

**Comment by Tracy6465** [comment]
the exception is : TTL exhausted
the pool is initialized only when the application is started for the first time in django.After each network request can use this pool to operate redis.

**Comment by Grokzen** [comment]
`TTL exhausted` is usually becuase you can't connect to the cluster. Either the cluster has changed and it do not know about the new IP addresses for some reason, for example if one shard is gone. You should try to correlate this error to any changes in the cluster and there is your problem.

For reference, the error is comming from here https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/client.py#L389 and it is not due to the connection pool

Another tip is to debug the following exception chain that starts from here https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/client.py#L358 to see what error you are really getting when the error happens.

**Comment by Grokzen** [comment]
@Tracy6465 I am closing this issue as it is not describing a real issue but more of a general question. If you still have a code problem that looks like a bug, please open a new issue.
