### ISSUE TITLE
Sunionstore blocked in cluster mode.

### ISSUE THREAD

**Issue by raunakb94** [Grokzen/redis-py-cluster#275]
I am trying to use pipelined command in cluster configurations where in i am seeing there are multiple commands blocked in cluster mode.

Is there any specific reason apart from that the destination of many commands might be on some other node and hence cause failure on redis.

but keeping in mind that redis allows custom hash based slotting using {} braces. and while implementing the command we ensure that the destination is also the same as the command keys. Then there should be not any problem with this approach ?

Do you see any kind of issue with this approach?

**Comment by Grokzen** [comment]
In principal, support for all commands should be possible in both non-pipeline and in-pipeline mode when using {} to prefix all commands to the same slot as per the redis documentation. When we did the first implementation of the pipelines, this was not something that we built in becuase it was much easier to just block out the multi slot commands to add them in at a later time either through a custom client implementation like some of the commands inside client.py, or by something similar to what you mentioned above. This is not something new that we did not know about at that time, it was just simpler to not do it at that time to get some kind of pipeline solution working.

In principal with how the solution works right now, the fix for it should be rather easy to solve as there is not really any needed customization in the pipeline side that needs to deal with anything special for the multislot commands. The only thing that really is needed to be added is the validation of all commands that in the case there is a multislot command, check if it resolves against the same slot and let it pass through.

**Comment by Grokzen** [comment]
I have no timeline when i can implement this on the pipeline side.

**Comment by raunakb94** [comment]
yes, exactly @Grokzen I had a similar approach in my mind.

That means I can extend the current Redis cluster client and create my own slotted pipeline class to unblock all the blocked commands. 

And everything should work fine if I guarantee while using the client that all the pipelined commands actually belong to the same slot.

**Comment by raunakb94** [comment]
A similar thing that you documented in [https://redis-py-cluster.readthedocs.io/en/master/pipelines.html#suggestion-three](url)

**Comment by Grokzen** [comment]
In theory yes, if you overwrite the blocking mechanism and add in your own variant to ensure same slot.

**Comment by raunakb94** [comment]
Great Thanks @Grokzen 
Your responses were blazingly fast.

**Comment by Grokzen** [comment]
If you do find a way to make a new subclass on your end and makes it work for you, please consider submiting a PR or atleast publish the branch so i can see if you are on the correct track for a proper implementation.

**Comment by raunakb94** [comment]
Yeah, I will submit the PR.
