### ISSUE TITLE
Single-slot cluster pub/sub?

### ISSUE THREAD

**Issue by jkaye2012** [Grokzen/redis-py-cluster#298]
Hi,

I've been reading a bit about Pub/Sub in Redis Cluster and in redis-py-cluster specifically. If I were to set up a cluster with a single node (but multiple slaves), would I be correct in assuming that things would function correctly across clients in different languages? My thought is that this would mean there is only a single hash slot for things to go to.

Secondarily, if the previous assumption is correct, what behavior should I expect in the case of a master failover with respect to subscriptions? Is this something handled by redis-py-cluster, or something that we should handle within our clients?

Thanks!

**Comment by Grokzen** [comment]
Technically you are correct yes, but the problem is worse and more complex then that. I would first suggest that you read up on the documenetation i have written about pubsub and why you should not use it in a clustered envrionment https://github.com/Grokzen/redis-py-cluster/blob/unstable/docs/pubsub.rst#scalability-issues

Note that the scaleability issues i have written about is valid up until 4.0.x redis series and i do not know if they have addressed any of the isuses or made any kinds of improvements for the big issues.

I have basically done 2 things in this client that addresses pub/sub solution.

1. I have made it so that each publish and subscribe message that is sent out, the client hashes the channel key to a slot and sends the message to that node in the cluster. Reason for this is that the hashing algorithm ensures that all clients sends publish and subscribe to the same node. But then you hit the problem described in the docs link above where messages is passed to all nodes in the cluster and the problem grows exponentional with the number of nodes. The second issue you hit is that this only works for full and non pattern channel keys. If you try to subscribe to a channel the entire solution breaks down. I guess that redis devs built the pub/sub solution to fan out all messages to all nodes to ensure that pattern subcsription would work w/o any modifications and with room for improvements at a later time.
2. I have made it very very very clear in the docs about my and this lib stance for pub/sub and that in the current form (up until redis 4.0.x), not saying that 5.0.x solves it that you should NOT be using pub/sub as it is primareally broken and need more work in order to be fully scaleable and usable.

Regarding the support and features of this lib, there is no additional logic or features or failover handling of subscriptions or listeners or anything like that. You basically would have to deal with that yourself right now if you want to build a solution on top of this lib, which i do not suggest you do.

My current suggestion when people ask for pub/sub support, is to stick with a 2 server solution. One server/cluster that you have your normal data and redis features etc on. It can be a single node, sentinel or clustered envrionment. Then run a fully seperate server that is non-clustered that only deals with pub/sub stuff. For any other higher scaleability requirements, i suggest that you look into some other tech that has this feature solved and/or built into itself, redis still has some way to go on this front.

**Comment by jkaye2012** [comment]
To my understanding, those scalability issues come into play only in clusters with more than one node. This would mean that a single-node cluster with multiple slaves for pub/sub would be functionally identical to a node running with slaves under a Redis Sentinel - please correct me if you believe that to be wrong. In this way, we would be using Cluster for more transparent failover only and not for hash slot selection.

My intention is to ensure that we are able to replicate an existing infrastructure driven by Redis Sentinel within Redis Cluster. It will not be a problem to send pub/sub traffic to a separate single-node cluster. This is in line with the two-server solution that you suggest and that I have read about elsewhere.

Handling failover of listeners is something that we have to do in non-clustered instances as well. I think it's relatively easy to handle on our client-side if the corresponding events are propagated from the underlying API (see https://stackexchange.github.io/StackExchange.Redis/Events for an example). I couldn't find anything like this that exists currently, but I'm happy to open a pull request to add some functionality like this if you're amenable.

**Comment by Grokzen** [comment]
Until redis server itself fixes the semi broken pubsub implementation and to fix this issue with pubsub nodes being routed to nodes that should not have the data, and that the entire procedure should be optimized internally by then, i will not attempt to make a pubsub solution that works inside a clustered envrionment but only when there is 1 shard node in the cluster. A sentinel solution works fine there as is. If redis solves their performance issues, a new issue and PR can be open at a later time if that is ever solved upstream. Pubsub should work normally and the same way in a non clustered envrinoment as well as in a clustered envrionment.
