### ISSUE TITLE
Getting TTL exhausted with AWS ElastiCache

### ISSUE THREAD

**Issue by martimarkov** [Grokzen/redis-py-cluster#310]
I'm getting `TTL exhausted` with AWS ElastiCache Redis 5 Cluster.

I've tried using the configuration endpoint from AWS as the host, tried adding all nodes in the shard to the `startup_nodes`, just the configuration endpoint to the `startup_nodes`. Nothing seems to be able to fix the issue. I'm running this inside EKS (AWS' Kubernetes service).

I have a separate app deployed which uses nodejs and that one behaves correctly and returns the data.

**Comment by Grokzen** [comment]
You need to debug out what exception you specifically are getting. The root cause is from this try/except block specifically https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/client.py#L364 and without known knowing which exception as what the content is of it, i can't help.

**Comment by unbeatedkb** [comment]
I have got the same error like it.

As you say, i tried to found the specifical exception. Since "ttl" in the try block, it will retry many times. I used pdb to debug it and found that they were MovedError and ConnectionError.

Specially, service that connected to redis cluster was deployed in my local docker and redis cluster was not. 

When i got MovedError, the "r" was like it.
![image](https://user-images.githubusercontent.com/18637307/52985429-bb7a3880-342e-11e9-901a-74c4a080fb6b.png)

And while ConnectionError with this one.
![image](https://user-images.githubusercontent.com/18637307/52985471-ed8b9a80-342e-11e9-8148-e84d62889646.png)

**Comment by Grokzen** [comment]
Yeah. The first error is a very common error and problem that many people encounter when they run stuff inside Docker. For some reason, redis inside a docker container have a tendancy to map all cluster nodes to 127.0.0.1 if all other nodes run inside the same container/envrionment. Technically this is correctly done by redis. But from the clients pov, this is wrong. What all cluster clients does is to ask the cluster for `CUSTER INFO` and/or `CLUSTER SLOTS` and parse the output. This output will say `Hi, your cluster nodes is located at 127.0.0.1:30002 ....` The problem here is that your clients will parse this and save this and belive that all redis nodes is at that address that redis says it is on. So when your client is on your host and not inside your container or from another machine, the client will pick up 127.0.0.1 and then you get the messages above.

There is a few different solutions for this. One is to not run all nodes in the same container, then redis is forces to track a real IP address that is reachable from the outside envrionment. It should track for example a 172.x.y.z.address between containers. Or you have to fix and run your code from the same machine so 127.0.0.1 lookups works.

MovedErrors is a expected result/output that in of itself it not wrong. It basically says that the current cluster cache that the client is holding is wrong and that you tried wrong or that you forced a lookup to the wrong node. This error resolves it self where when it get this back it will try the new node that the cluster tells you to talk to.

What can happen tho is if your nodes points to wrong addresses like the :30001 port points to a proper ip address and 30002 points to 127.0.0.1 or something else wrong and that is why it can't look it up properly.
