### ISSUE TITLE
Use redis-py version above 3.3.0

### ISSUE THREAD

**Issue by toughrogrammer** [Grokzen/redis-py-cluster#334]
I'm using `redis-py-cluster` 2.0.0 but I need `redis-py` 3.3.0 above version. By `redis-py` 3.3.0, `health_check_interval` option is added. Is there any reason that `redis-py-cluster` need to use below 3.1.0 version?

**Comment by Grokzen** [comment]
When developing the latest major release of this client lib, the goal was to get to 3.0.0 at least so the new features in there could be used. Due to the many changes in 3.1.x and above i decided not to take that in the same release as the work to port everything would be to great in one big batch. Release 2.1.0 aims to support up to latest in 3.3.x release. If you check the latest commit in the master branch, you can build a version that allows you to use any release in the 3.x.x track, but i think that the code is broken when using anything above 3.1.x.
