### ISSUE TITLE
Support blocking connection pool

### ISSUE THREAD

**Issue by toughrogrammer** [Grokzen/redis-py-cluster#340]
There is `BlockingConnectionPool` in `redis-py` but here isn't. I'm facing connection spike situations and it makes redis server halt. Is it hard to implement blocking connection pool of cluster version?

**Comment by Grokzen** [comment]
@toughrogrammer I do not know, i have no immidiate plans on building a `BlockingConnectionPool` myself for any upcomming releases. You can look at the cluster connection pool https://github.com/Grokzen/redis-py-cluster/blob/master/rediscluster/connection.py#L97 and compare it to the upstream connection pool that it inherits form and see the general differences between them. Kinda the same things have to be supported and implemented in a Blocking pool.

It dont look super complex to implement and probably most things you need to sort out is to get the correct connection and bookkeep it correctly since we need to track ocnnections to multiple nodes and then implement a working blocking solution for it.

If you want to take a stab at it and make a working implementation, PR:s is much appreciated.

**Comment by Grokzen** [comment]
PR has been submited, merged and will be part of next major release
