### ISSUE TITLE
Connection still in close_wait

### ISSUE THREAD

**Issue by aasifalam** [Grokzen/redis-py-cluster#341]
Using 
redis-py-cluster = 1.3.6
server = 4.0.14

we are seeing many connection at the application in CLOSE_WAIT state. So many that application pod runs of all the file descriptors. Restart is the only option. 
At the Redis server there are no dangling connection to the clients however. We are seeing this issue with multiple applications using redis-py-cluster client

**Comment by Grokzen** [comment]
@aasifalam This is not a issue that this lib is responsible for. The underlying connection logic and polling and release magic is done by upstream package `redis-py`. There seems to be some work done in redis--py 3.2.0 release and beyond. It says it should help to sort this kind of issue out, but i have not really tested it.

The root cause of this issue in a clustered envrionment is that we open up a ton more connections and faster since we talk to many more nodes in a cluster, so the bigger your cluster, the faster it would get to this point where it would give the errors you are having.

There is nothing or barley anything this lib can do for these kinds of things in reality and it is something upstrema has to fix.

Redis-py support up to 3.3.x is planned for redis-py-cluster 2.1.0 but there is no timeline when that work is finally done and out for general consumption.
