### ISSUE TITLE
Redis cluster through ssh tunnel

### ISSUE THREAD

**Issue by Frantch** [Grokzen/redis-py-cluster#364]
Hello,

in order to reach my cluster (2 nodes) I need to open an ssh tunel           
 
`ssh -J xxxx:1234 xxxxx -L 7779:$REDIS_HOST:$REDIS_PORT`

Now I'm facing an issue where commands something (even more often than not) fail with this error

> rediscluster.exceptions.ClusterError: TTL exhausted.

Most probably I'm getting this error because the cluster is telling the client to move to an other node and of course it will try to connect on the real node uri and not 127.0.0.1

Is it possible with this client to 'map' the node addresses? Something like telling it if you receive node address 'x' replace connect instead to 127.0.0.1?

Or any other workaround that would allow me to 'always' connect to 127.0.0.1 ?

Thank you!

**Comment by Grokzen** [comment]
@Frantch No, there is no mechanism inside the client to rebind nodes. In the end, this is not an issue with the client itself, the problem is what IP:s that redis-server tracks internally behind your tunnel.

I have sucha feature to allow for remapping on the agenda/backlog for a future release, but it wont make the cut for this next release tho. One thing that you can try tho but that probably wont work out super duper in the end is to specify all the node addresses in your startup_nodes argument, but then add `init_slots_cache=False` to the client to stop it from initialize, but i am not sure if it will try to initialize at a later time, or if it will only use the startup nodes all the time. The problem is when a node fails like you mention, becuase then your startup nodes will not know what to do as it will be missing the new node. So there is not really a good solution for this right now either on the client side or on the server side of things.

**Comment by Grokzen** [comment]
@Frantch Have a look at this new commit that i just pushed 9321d49660fe96696892660436aeeb2f7a2d5cb1 it should most probably solve your use-case where you need to route the traffic through an SSH tunnel. If you find any problem with this feature then please open up a new issue describing the issue if this new code do not work properly for this use-case.
