### ISSUE TITLE
how to use connection pool in cluster mode

### ISSUE THREAD

**Issue by vangoleo** [Grokzen/redis-py-cluster#366]
Hello, I have some problem on how to use Connection Pool while using redis-py-cluster, Could you give me some help, thanks^_^

I know that we can use Connection Pool while connect to a single redis node, below is the code snippet:
```python
pool = redis.ConnectionPool(host='127.0.0.1', port=6379)
r = redis.Redis(connection_pool=pool)
```
In the above code, redis client use a connection pool, to avoid extra network overhead.

But it seems there is no document talking about how to use connection pool in redis-py-cluster. 

```python
r = StrictRedisCluster(startup_nodes=redis_nodes, decode_responses=True)
r.get("aaa")      // create a new connection and then close it while request is finished.
r.get("bbb")      // create a new connection and then close it while request is finished.
...
r.get("zzz")      // create a new connection and then close it while request is finished.
```

Can anybody supply some explain or simple demo. 
Also, how to use both Pipeline and Connection Pool in redis-py-cluster.

Thanks.

**Comment by Grokzen** [comment]
@vangoleo You must use one of the connectionpools defined in this file https://github.com/Grokzen/redis-py-cluster/blob/master/rediscluster/connection.py as you need a proper cluster compatible connection pool in order to use it whit this lib. So create an object instance of `ClusterConnectionPool` then pass that object into `RedisCluster(connection_pool=your_cluster_pool)` and then you can use anything and everything as you want.

But do note that there is no need to create an connectionpool from outside the RedisCluster object as if you pass in startup_nodes to your cluster client, it will automatically create a pool for you in the same way that `redis-py` creates a pool for you. Unless you subclass the pool class and change any functionality in your pool, this step is not needed and redundant.

Pipelines works the exact same way in a cluster as they do in a non-clustered environment, create your client class and then create a pipeline object and then send your commands into it and execute. You can use basically any normal non-clustered example of a pipeline inside a clustered environment. Do note that there is a ton of internal and technical differences when using a clustered pipeline compared to a normal pipeline, and there is plenty of docs that you should read up on inside the docs/ folder in this project that can lead you to what you need to know and understand about using them in a cluster.

**Comment by sidSingla** [comment]
It will be good to actually have a working example of this. It is very confusing and takes time to get hands-on else.

**Comment by Grokzen** [comment]
@sidSingla There is thousands of examples through google. ConnectionPools work exactly the same as they do up in redis-py. The pool just passes through this lib on its way to redis-py. If you know how to make one of them there, you know how to make one here and customize it to your liking.

**Comment by guytubul86** [comment]
@sidSingla  Can you give an example?

**Comment by Grokzen** [comment]
There will be no specific example made here by my at least for this. ConnectionPools works basically the same between redis-py and this lib. You can make your own class if you want to implement custom logic (which is already a super advance use-case and should not be done unless you really need to or know exactly what you are doing) so there is not really a general example i would provide that would be used by the general public any way. So if you want a example of this in any way, then you will have to dig into the code here, or in redis-py to understand how custom ConnectionPools work, and i reitterate, there is tons of examples and code and threads that is easily searchable on google or stackoverflow in how to do and work with this feature.

If you really want to have a example file, then make one and submit it through a PR here and i will have a look at it.
