### ISSUE TITLE
ERROR sending 'cluster slots' command to redis server AttributeError: 'RedisCluster' object has no attribute 'connection'

### ISSUE THREAD

**Issue by victorzhucompass** [Grokzen/redis-py-cluster#370]
with ssh: ssh -L 6379:<redis-endpoint>:6379 username@bastions.company.com
r = redis.Redis(password=redis_password, ssl_cert_reqs=None, ssl=True, decode_responses=True)
connect successfully

switch to cluster

startup_nodes = [{"host": '127.0.0.1', "port": 6379}]
r = RedisCluster(startup_nodes=startup_nodes, decode_responses=True, password=redis_password, ssl=True)

error: ERROR sending 'cluster slots' command to redis server: {'host': '127.0.0.1', 'port': 6379}
Exception ignored in: <function Redis.__del__ at 0x1224305f0>
AttributeError: 'RedisCluster' object has no attribute 'connection'

**Comment by Grokzen** [comment]
@victorzhucompass I need a full stack trace to be able to determine the problem and possible cause of this issue. From what i can see, you problem is in the upstream package redis-.py and not here based on `<function Redis.del at 0x1224305f0>` exception/error you are getting.
On a site note, why are you not using the same arguments int he cluster version? you have removed `ssl_cert_reqs=None` in the cluster version of things. Try adding that back again.

Also please note what versions of all the components you are using, redis-py-cluster, redis-py, redis-server, operating system etc, anything that might be usefull to me.

**Comment by victorzhucompass** [comment]
Successfully installed redis-3.0.1 redis-py-cluster-2.0.0

ERROR sending 'cluster slots' command to redis server: {'host': '127.0.0.1', 'port': 6379}
Exception ignored in: <function Redis.__del__ at 0x122448cb0>
Traceback (most recent call last):
  File "/Users/victor.zhu/opt/anaconda3/envs/roomtype/lib/python3.7/site-packages/redis/client.py", line 885, in __del__
    Delete all keys in the current database.
  File "/Users/victor.zhu/opt/anaconda3/envs/roomtype/lib/python3.7/site-packages/redis/client.py", line 888, in close
    executed asynchronously by the server.
AttributeError: 'RedisCluster' object has no attribute 'connection'

**Comment by Grokzen** [comment]
The stacktrace shows that it is a problem with the upstream package redis-py as the error originates from in there. I dont know really why the `def del(...)` method is really called in your case, but it seems like you are doing some secondary command over the client initialize command. The bouncing of commands is a bit tricky when going around between the libraries. In essence you have problem and you have to figure out why you can't connect to your nodes, start there and the exception will go away by itself. A tip is to make the cluster object and then just do a simple get/set operation to see if that helps out or not.

A possible temporary solution that you can attempt is to send this into your RedisCluster instance `skip_full_coverage_check=True` it is not optimal, but it might just make it work for now. I think i might know what could cause it.

For me to be able to replicate this problem, can you provide what redis-server config you have in order to setup the ssl/certs part so i can spin up a similar instance locally and run the tests to see if i can replicate the issue myself on my end?

**Comment by Grokzen** [comment]
@victorzhucompass Your issue is most probably the same issue as issue 1339 in the redis-py project. The error is very similar in nature and stack-trace from what they have in that issue. I will close this one as the fix in their code should help to resolve the problem.

**Comment by Grokzen** [comment]
https://github.com/andymccurdy/redis-py/issues/1339
