### ISSUE TITLE
Error using ssl option in RedisCluster. (got an unexpected keyword argument 'ssl')

### ISSUE THREAD

**Issue by umang92** [Grokzen/redis-py-cluster#381]
Here is my code to create RedisClient

```
RedisCluster(startup_nodes=startup_nodes,
                                                                 password="password",
                                                                 skip_full_coverage_check=True,
                                                                 ssl=False)

```

Error while executing commands like RPUSH:
__init__() got an unexpected keyword argument 'ssl'

Stacktrace:

```
return self._with_retry(lambda: self._client.rpush(self._topic, _bytes))\n', '  File "/app/python/sensei_sdk/_internal/streams/redis_stream.py", line 20, in _with_retry\n    return func()\n', '  File "/app/python/sensei_sdk/_internal/streams/redis_stream.py", line 36, in <lambda>\n    return self._with_retry(lambda: self._client.rpush(self._topic, _bytes))\n', '  File "/app/python/newrelic/hooks/datastore_redis.py", line 65, in _nr_wrapper_Redis_method_\n    return wrapped(*args, **kwargs)\n', '  File "/app/python/newrelic/hooks/datastore_redis.py", line 65, in _nr_wrapper_Redis_method_\n    return wrapped(*args, **kwargs)\n', '  File "/app/python/redis/client.py", line 1609, in rpush\n    return self.execute_command(\'RPUSH\', name, *values)\n', '  File "/app/python/rediscluster/utils.py", line 101, in inner\n    return func(*args, **kwargs)\n', '  File "/app/python/rediscluster/client.py", line 395, in execute_command\n    r = self.connection_pool.get_connection_by_node(node)\n', '  File "/app/python/rediscluster/connection.py", line 325, in get_connection_by_node\n    connection = self.make_connection(node)\n', '  File "/app/python/rediscluster/connection.py", line 232, in make_connection\n    connection = self.connection_class(host=node["host"], port=node["port"], **self.connection_kwargs)\n', '  File "/app/python/rediscluster/connection.py", line 47, in __init__\n    super(ClusterConnection, self).__init__(*args, **kwargs)\n']
```

I am using redis-py-cluster==2.0.0

**Comment by Grokzen** [comment]
@umang92 Please try the 2.1.0-rc1 release or latest commit on the master branch instead, the error is fixed in there

**Comment by umang92** [comment]
Thanks, Grokzen. That's good to know.

By when would this release be pushed out to PyPI? Actually we build
everything inside a docker. Without PyPI, I will need to copy the complete
code there and build it. Is there a better way I can use this?

**Comment by Grokzen** [comment]
@umang92 In your requirements file you can simply put in this i think

`https://github.com/Grokzen/redis-py-cluster/releases/download/2.0.99/redis_py_cluster-2.0.99-py2.py3-none-any.whl` as a requirement and pip will download it from that url and install it. Otherwise use the official way of pointing the requirements.txt to the github project url and just tell it to use the tag 2.0.99

**Comment by umang92** [comment]
@Grokzen Even with the version 2.0.99. I am getting the same error. Please note that RedisCluster object is created successfully. But when I call functions like rpush(), I get this error. StackTrace for the same is given above. Do think it can be something else?

**Comment by Grokzen** [comment]
@umang92 Then you need the latest commit in the master branch 707ae23d32f98c172b2c39c4b4ad0f0cbf8ebb57 that was done after the 2.0.99 release. Please try it by using the same method above but pointing it to that commit specifically or to the master branch in general

**Comment by umang92** [comment]
okay. 
1. I had tried requirements.txt approach. But with that I start getting "No Module named rediscluster". Even though I can see that the dependency 2.0.99 wa ssuccessfully installed.

2. Then I tried an approach of using dependency links in the setup.py file. Something like this ```
install_requires=['apscheduler==3.5.3', 'protobuf==3.6.0', 'boto3==1.9.79', 'requests_toolbelt==0.9.1',
                  'supervisor==4.2.0', "newrelic==4.18.0.118",
                  'redis-py-cluster>2.0.0'],
dependency_links=[
                'git+https://github.com/Grokzen/redis-py-cluster.git@2.0.99#egg=redis-py-cluster-2.0.99',
            ]```
With this actually I realized that the dependency links that I was using were getting ignored and it was still picking 2.0.0. To use dependency links in setup.py we need to use a special flag in pip (--process-dependency-links). But this flag is available only in old version of pip<=18. 

Now I will need to try the option#2 with an old version of pip and the special flag --process-dependency-links.

**Comment by Grokzen** [comment]
2.0.99 was never released on pypi where the requirements file pulls down from. The latest stable release on pypi is still 2.0.0 right now. I dont get why you would need dependency_links tho. It might be one weird quirk with the difference between specifying the dependency in the setup.py file instead of in a requirements.txt file and use the `-r <file>` option with pip install. I am sure that pip and setup.py have not really removed the option for it. You should not have to downgrade pip imo, it should be supported somehow in the newer release, but you might have to install the release before you get into your setup.py file. I guess you will have to play around with it some to find a solution that works.
