### ISSUE TITLE
get wrong return value "OK" from redis

### ISSUE THREAD

**Issue by heliusjing** [Grokzen/redis-py-cluster#497]
I got wrong result of str "OK" from redis，This phenomenon is accidental
redis-py-cluster:1.3.6
python:2.7.5

**Comment by Grokzen** [comment]
This report is impossible to act on. There is no steps to reproduce the error, no code, no commands that errors out, what code path etc. This is needed in order to help debug any issues. Also note that 1.3.6 is an old version and running it at python 2.7 is very discouraged and any code issues there is not supported by me any longer. Please submit a new issue with any and all information needed to reproduce the bug.
