### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rlvoyer** [Grokzen/redis-py-cluster#63]
Is this project still active? Are you accepting pull requests / additional contributors? Are you intending for to re-implement all of the functionality in redis-trib.rb? For example, add_node, remove_node, and reshard?

**Comment by Grokzen** [comment]
@rlvoyer Hi. Yes this project is kinda active :] 

Any contributions will be reviewed and merged if they are in line with the rest of the code and all that.

I am not sure what the purpose of re-implementing `redis-trib.rb` to python would give more than for the fun of it :] Do you want to make the cluster management more programmable for python environments or do you have any other purpose in mind why you would like to do this? If you would like to elaborate on the why and how and so in a new issue i will look at it.

Why i have not commited anything to this repo is because most of my time is splitted in several different areas right now, OSS projects (salt related), work projects, other personal side projects. I have also not given so much time for this because i find the code very stable right now and i know atleast one person who use it in production with ~40 server setup and he have said that it works very well and he have even witnessed node drops and reshards in the wild and this client handles it very well. So because of the proven stability i do not know what to spend time on in this code :] Ofc there is areas where it can improve to provide minor new functionality or bring the code closer to how redis-py is built.

When i find some time i will try to work on some of the issues but i can't guarantee anything right now :]

**Comment by Grokzen** [comment]
@rlvoyer If you want to have a chat instead of having the discussion in here i am allways available on gitter. See the gitter link at the top of the README file and just ping me with @grokzen in there and we can talk about redis-trib.rb
