### ISSUE TITLE
inaccurate example info in readme.md

### ISSUE THREAD

**Issue by andyxning** [Grokzen/redis-py-cluster#68]
as with redis-py-cluster 0.2.0, there is no StricRedisCluster class instead RedisCluster. So the `Usage example` section in **readme.md** should be updated.

I think we should also state the version of redis-py-cluster with which the example is illustrated.

```
>>> from rediscluster import StrictRedisCluster
>>> startup_nodes = [{"host": "127.0.0.1", "port": "7000"}]
>>> rc = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True)
>>> rc.set("foo", "bar")
True
>>> rc.get("foo")
'bar'
```
updated to 
```
>>> from rediscluster import RedisCluster
>>> startup_nodes = [{"host": "127.0.0.1", "port": "7000"}]
>>> rc = RedisCluster(startup_nodes=startup_nodes, decode_responses=True)
>>> rc.set("foo", "bar")
True
>>> rc.get("foo")
'bar'
```

**Comment by Grokzen** [comment]
If you look in the tag for 0.2.0 or the master branch at https://github.com/Grokzen/redis-py-cluster/tree/0.2.0 you will see that both the code and the readme uses `RedisCluster` and not `StrictRedisCluster`

The readme you see in when you view the repo is the updated once that belongs to `unstable` branch and it also is correct where `RedisCluster` was renamed to `StrictRedisCluster` to make it more compatible with how redis-py names their classes.

About stating what version examples is made from that is irrelevant imo because if you are using a tagged 0.2.0 you should really check the readme/docs for that version and not development trunk :]

**Comment by andyxning** [comment]
Correctly. sorry for misunderstanding that.
