### ISSUE TITLE
is support Transaction？

### ISSUE THREAD

**Issue by rfyiamcool** [Grokzen/redis-py-cluster#69]
is support Transaction？

**Comment by rfyiamcool** [comment]
And   How about his performance？

**Comment by Grokzen** [comment]
Hi @rfyiamcool Please read the docs and specially this section https://github.com/Grokzen/redis-py-cluster/blob/unstable/docs/Pipelines.md#transactions-and-watch that might describe some and give awnswers to your question.

The short awnser is that it kinda depends on what level of transaction you are looking for. Let me give you some examples.

The highest level of transactions that is normally used today with a pipeline is that you want the entire pipeline to be transactional and if some error occurs with any command it should be rolled back. This in a redis cluster is not possible because the problem is that you need to send a seperate transaction to each node in the cluster and they are execute seperatly and you can't for example "load" a pipeline into redis --> wait for confirmation that all nodes have loaded the pipeline and then trigger the execution from the client and they will be all commited or rolledback.

If you however are looking for Node level transaactions where if you construct a pipeline and then want each node to execute a transaction that is possible to support but i would not recommend it because it is not a real transaction support and you can't do a rollback on all pipelines across the cluster once they are commited.

Transactions are tricky and not easy to implement :] I hope this answers your question. Please close the ticket if it did or ask away if you have any other questions regarding this topic.
