### ISSUE TITLE
The use of connections

### ISSUE THREAD

**Issue by iandyh** [Grokzen/redis-py-cluster#85]
Currently the cluster client maintains a batch of `Redis.Connection`s in a `Redis.ConnectionPool`.

Is there a reason not to use the `Redis` object directly? Since it itself maintains a pool of connections.

With the current design, there is actually a bug when the connection is gone due to network issues. As a result, the connection cannot self-repair in such circumstance. I had a fix in my branch, which is to catch `Timeout` error and reset the connection pool. It's a dirty fix, but it works.

The better way to maintain the connections is probably like this: `connections = {node: Redis(host, port)}`.

**Comment by Grokzen** [comment]
I am not sure i get the problem you are seeing?

If i am understanding it, you want to change from the custom RedisCluserConnection class to use a regular Redis object for each connection to a node in the cluster? I kinda get it that each node would handle their own connections with the currently implemented connection pool and it would maybe reduce the code some, but you would still need the cluster management layer on top of everything to cordinate the key/hash/slot management, redirection logic and similar things.

There would be some tradeoffs with this solution, you might get the connection handling and pooling for free but you loose the global connection pool and would have to build logic around that.

I have to think some about this before doing anything.

I looked at the commit in your branch and if you think it might improve things because of a inconsistency or bug, then you should submit it to a PR.

**Comment by iandyh** [comment]
Sorry. I should've provided code.

If you were looking at the commit: https://github.com/iandyh/redis-py-cluster/commit/13ba59402ead87c811a8020deb93506b0aac808d , then this is the current fix. But I regard it as dirty and overkilled. I'll explain as below:

1. Because of network problem, you will encounter errors when executing commands on all nodes, e.g. `info`. The `Redis` object has already handle this out of the box(including retry option). Currently, `redis-py-cluster` will throw the exception and put the broken connection back to the connection pool. However, the broken connection should be disconnected and discarded. 

2. The fix in my branch simply catches the exception and reset the entire connection pool, which is a dumb fix and can be expensive in production. Therefore I didn't submit a PR. Ideally, we want to only reset the connection of specific node.

The reason why I purposed to use `Redis` object is that it has already handled the connection problem and we can reuse that part. But certainly, it comes with a cost. We cannot simply inherit the `Redis` class. Instead, we need to map all the commands to the corresponding methods. Moreover, the reset logic will be totally different as well.

Cheers.

**Comment by Grokzen** [comment]
I have been thinking some, and i am not incline towards rebuilding the connection pool to use regular redis instances and the underlying connection pool. The main point why i do not want to do it is that the overall longtime goal is to have the code as close to the coding standard and structure of redis-py so that when it is possible in the future this code could almost be copy/pasted into redis-py and it will just work without major rebuilding of the code.  By changing the connection logic to use Redis instances it might make it easier to work with connection pooling here but the code still have to be rebuilt when/if merged into redis-py.

The other major thing that i might be more incline to do is to copy the entire connection pool code from redis-py and include it here and add the cluster specific code into the same code so that instead of inherit the functionality and override it where we need they are merged.

**Comment by Grokzen** [comment]
@iandyh Would you agree that we can close this issue when #86 is merged into unstable?

**Comment by iandyh** [comment]
@Grokzen I have a mixed feeling though. One hand I think it's still easy to merge it back to redis-py with reusing of connection from redis-py. On the other hand, the significant change will bring down the stability of the current client. And stability is really important here so we might want to stay as it is.
