### ISSUE TITLE
How to use pipeline when all commands are guaranteed to be in 1 slot/server ?

### ISSUE THREAD

**Issue by ddorian** [Grokzen/redis-py-cluster#99]
Hi,

I think sharding has to be considered really carefully, which I have, and my pipeline commands are guaranteed to go to one server/slot. Is there a way I can crate a pipeline where I guarantee that all commands will go to 1 server and no logic is executed that will group the commands by node? I saw docs and code but couldn't find anything.

Thank you

**Comment by Grokzen** [comment]
Hi. There is no way to do this right now because the implementation is done to be generic and allow multi node/slot keys inside the same pipeline. But, to support this feature is something that i have been thinking about for a while, because it would rather easy to do by doing another class that inherits from the current pipeline class but replaces the execute function with a new function with your more basic logic. I have been thinking about doing something similar in the normal client for multi key commands. This is the way all other clients have implemented the client and pipelines. It would mean that it would provide a basic solution for both cases that have this way of dealing with keys. Then you would extend that functionality with a class that sits ontop of that basic class where all the new and fancy logic is implemented where it deals with multi node keys. With this design the user could choose what level of support and complexity it want.

**Comment by Grokzen** [comment]
I will close this when the above referenced PR is closed. It improves the situation with pipelines alot and cuts alot of overhead when dealing with any number of nodes.

**Comment by Grokzen** [comment]
Closing because of merged PR
